// Generated by Wrangler on Tue Jun 04 2024 19:53:39 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	ALLOW_OTHER_HOSTS: "img.srkyxk.com,img.kemono.games";
}
