name = "cf-image-proxy"
account_id = "bfe6a54d9224134a05830fad09110e3c"
main = "src/index.ts"
compatibility_date = "2024-05-29"
[placement]
mode = "smart"
[dev]
port = 4000
[vars]
ALLOW_OTHER_HOSTS = "img.srkyxk.com,img.kemono.games,dummyimage.com,placehold.co"
ALIYUN_MODERATION_REGION = "cn-shanghai"
ALIYUN_MODERATION_SERVICE = "postImageCheckByVL_ec_01"
[[kv_namespaces]]
binding = "PIXIV_MODERATION"
id = "d121ee52e8de48748dfd98cf7dee3ceb"
[[r2_buckets]]
binding = "IMG_CACHE"
bucket_name = "cf-image-proxy-cache"
